# FFMPEG sends out the data in bursts. Sometimes, the interval between bursts can be over 50ms. We
# need to set our buffers large enough to handle these

CONFIG_NET_PKT_RX_COUNT=64
CONFIG_NET_BUF_RX_COUNT=64

CONFIG_I2S_TX_BLOCK_COUNT=128
CONFIG_RTP_AUDIO_STREAM_SAMPLE_N_BLOCKS=128
CONFIG_RTP_AUDIO_STREAM_SAMPLE_JITTER_BUFFER_SIZE=64
CONFIG_RTP_AUDIO_STREAM_RX_MSGQ_SIZE=128
